#!/usr/bin/ksh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2026 Klaus Ziegler. All rights reserved.
#

# =============================================================================
# =============================================================================
# sparc_usb_confiure - Configure a populated boot archive area including usr
#			and misc filesystems into a usable boot archive.
# =============================================================================
# =============================================================================

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Main
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Configure a populated boot archive area into a usable boot archive, less archiving.
# 
# Args:
#   MFEST_SOCKET: Socket needed to get manifest data via ManifestRead object
#
#   PKG_IMG_PATH: Package image area
#
#   TMP_DIR: Temporary directory to contain the boot archive file
#
#   BA_BUILD: Area where boot archive is put together.
#
#   MEDIA_DIR: Area where the media is put. (Not used)
#
# Note: This assumes a populated boot archive area exists at $BA_BUILD.
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Verify argument count
if [ $# != 5 ] ; then
	print -u2 -f "%s: Requires 5 args: Reader socket, pkg_image area,\n" \
	    "$0"
	print -u2 "    tmp dir, boot archive build area, media area,"
	print -u2 "    img_type_file."
	exit 1
fi

# Get commandline args.  First 5 are passed to all finalizer scripts.
MFEST_SOCKET=$1
PKG_IMG_PATH=$2
if [ ! -d $PKG_IMG_PATH ] ; then
	print -u2 -f "%s: Image package area %s is not valid\n" \
	    "$0" "$PKG_IMG_PATH"
	exit 1
fi

TMP_DIR=$3
if [ ! -d $TMP_DIR ] ; then
	print -u2 -f "%s: Temporary area %s is not valid\n" "$0" "$TMP_DIR"
	exit 1
fi

BA_BUILD=$4
if [ ! -d $BA_BUILD ] ; then
	print -u2 -f "%s: Boot archive build area is not valid\n" "$0"
	exit 1
fi

builtin cd
builtin rm
builtin mkdir
builtin mv

# Define a few commands.
CHGRP=/usr/bin/chgrp
CHOWN=/usr/bin/chown
GREP=/usr/bin/grep
LOFIADM=/usr/sbin/lofiadm
MKISOFS=/usr/bin/mkisofs
TIME=/usr/bin/time

# Define non-core-OS commands.
MANIFEST_READ=/usr/bin/ManifestRead

# Note that DIST_ISO_SORT may or may not exist, given the type of image.
DIST_ISO_SORT=$($MANIFEST_READ -k $MFEST_SOCKET "iso_sort")

if [ ! -d $PKG_IMG_PATH ] ; then
	print -u2 -f "%s: Image package area %s is not valid\n" \
	    "$0" "$PKG_IMG_PATH"
	exit 1
fi

cd $PKG_IMG_PATH

# check package dependencies for perl, a combined / and /usr image
# with two perl version, will simply be to big to be booted.
NUMVERS=`(cd usr/perl5; ls -1 | sed \
	-e "/bin/d" \
	-e "/man/d" \
	-e "/pod/d" \
	-e "/site_perl/d" \
	-e "/vendor_perl/d" | wc -l | awk '{print $1}')`

if [ "$NUMVERS" -ne 1 ]; then
	PVERS=`(cd usr/perl5; ls -1 | sed \
		-e "/bin/d" \
		-e "/man/d" \
		-e "/pod/d" \
		-e "/site_perl/d" \
		-e "/vendor_perl/d")`
	print -u2 -f "%s: \nImage package area: %s\ncontains more than one Perl-Version:\n%s\n" \
	    "$0" "$PKG_IMG_PATH" "$PVERS"
	# try to find out which packages depend on the older version.
	cd ${PKG_IMG_PATH}/var/pkg/publisher/openindiana.org/pkg
        rm -rf library%2Fperl-5%2F*
	cd ${PKG_IMG_PATH}/usr/perl5
	for VERS in `ls -1 | sed \
		-e "/bin/d" \
		-e "/man/d" \
		-e "/pod/d" \
		-e "/site_perl/d" \
		-e "/vendor_perl/d" \
		-e "s@\.@@g" | sed '$d'`
	do
		cd ${PKG_IMG_PATH}/var/pkg/publisher/openindiana.org/pkg
		rm -rf runtime%2Fperl-${VERS} consolidation%2Fuserland%2Fuserland-incorporation
		print -u2 -f "Dependencies for: runtime/perl-%s need to be fixed.\n" "$VERS"
		cd ${PKG_IMG_PATH}/var/pkg/publisher/openindiana.org/pkg
		find . -type f -exec grep "runtime/perl-${VERS}" {} \; -print
	done
	print -u2 "Please check detail-log for list of packages." 
	cd $PKG_IMG_PATH
	exit 1
fi

# sbin, kernel and lib are all in the root archive
print "Removing sbin, kernel and lib from package image area"
rm -rf sbin kernel lib tmp/tmp_*

# before we can compress /usr we need to save some essential
# things needed for the installer.
cd ${PKG_IMG_PATH}/usr
# keyboard
mv share/lib/keytables ..
# terminal unfortunately both databases are needed.
mv share/lib/terminfo ..
# time
mv share/lib/zoneinfo ..
# needed to intialize SMF
mv share/lib/xml ..
# hal SMF services needs dbus
mv share/dbus-1 ..
# prtconf needs share/hwdata/pci.ids
mv share/hwdata ..

D2REM="apache2 apr apr-util ddu demo dict games has kvm mail man net"
D2REM="$D2REM news old openssl/3/share perl5 preserve proc pub sfw"
D2REM="$D2REM share spool src X11 lib/p7zip lib/iconv gnu/share/info"
D2REM="$D2REM gnu/share/locale gnu/share/man gnu/share/tabset"

for d in $D2REM
do
	[ -d $d ] && printf "$d " >> /tmp/boot_archive_compress_usr.$$
done

# only keep libicuuc.so/libicudata.so in solaris.zlib for zpool/zfs commands.
cd lib/64
mv libicuuc.so.* ../../..
mv libicudata.so.* ../../..
cd ../..
echo "lib/64/libicu*" >> /tmp/boot_archive_compress_usr.$$

/usr/bin/gtar cf usr.tar `cat /tmp/boot_archive_compress_usr.$$`

# now clear out usr.
rm -rf `cat /tmp/boot_archive_compress_usr.$$`
rm /tmp/boot_archive_compress_usr.$$

print "Compressing usr directories using lzma compression"
xz -9 usr.tar
if [ $? -ne 0 ] ; then
	print -u2 -f "%s: compression of usr directories failed\n" "$0"
	exit 1	
fi
# move compressed /usr into dotfile /.usr.tar.xz
mv usr.tar.xz ${BA_BUILD}/.usr.tar.xz
mkdir -p share/lib
$CHGRP sys share
$CHGRP sys share/lib
$CHGRP bin include
mv ../dbus-1 share
mv ../hwdata share
mv ../keytables share/lib
mv ../terminfo share/lib/terminfo
mv ../xml share/lib
mv ../zoneinfo share/lib
mv ../libicuuc.so.* lib/64
mv ../libicudata.so.* lib/64

cd $PKG_IMG_PATH

# sbin, kernel and lib are all in the root archive
print "Removing sbin, kernel and lib from package image area"
rm -rf sbin kernel lib tmp/tmp_*

print "Generating usr filesystem image"
if [ ! -d $PKG_IMG_PATH ] ; then
	print -u2 -f "%s: Image package area %s is not valid\n" \
	    "$0" "$PKG_IMG_PATH"
	exit 1
fi

if [[ "X${DIST_ISO_SORT}" != "X" && -s "${DIST_ISO_SORT}" ]]; then
	SORT_OPTION="-sort $DIST_ISO_SORT"
	print "Sorting according to $DIST_ISO_SORT"
else
	SORT_OPTION=""
fi

$MKISOFS -o solaris.zlib $SORT_OPTION -quiet -N -l -R \
    -U -allow-multidot -no-iso-translate -cache-inodes \
    -d -D -V "compress" usr

if [ $? -ne 0 ] ; then
	print -u2 -f "%s: mkisofs of solaris failed\n" "$0"
	exit 1	
fi

print "Confirm lofiadm is available in image..."
if [ ! -f ${PKG_IMG_PATH}${LOFIADM} ] ; then
	print -u2 -f "%s: %s%s NOT FOUND\n" "$0" "${PKG_IMG_PATH}" "${LOFIADM}"
	exit 1
fi

LOFI_OUT_STR=${TMP_DIR}/lofi_out_str.$$

USER_ZLIB_ALG=lzma
print "Compressing usr filesystem image using compression algorithm: ${USER_ZLIB_ALG}"
LD_LIBRARY_PATH=${PKG_IMG_PATH}/usr/lib $TIME ${PKG_IMG_PATH}/${LOFIADM} \
    -C ${USER_ZLIB_ALG} ${PKG_IMG_PATH}/solaris.zlib >/dev/null \
    2>$LOFI_OUT_STR
if [ $? -ne 0 ] ; then
	$GREP "invalid algorithm name" $LOFI_OUT_STR
	if [ $? -eq 0 ] ; then
		print -u2 -f "%s: %s is an invalid lofiadm algorithm\n." \
		    "$0" "${USER_ZLIB_ALG}"
		print -u2 "Please modify your USER_ZLIB_ALG parameter."
		rm $LOFI_OUT_STR
		exit 1
	fi
	rm $LOFI_OUT_STR
	print -u2 -f "%s: compression of usr filesystem failed\n" "$0"
	exit 1	
fi
rm $LOFI_OUT_STR
mv ${PKG_IMG_PATH}/solaris.zlib ${BA_BUILD}

print "Generating misc filesystem image"
if [ ! -d $PKG_IMG_PATH ] ; then
	print -u2 -f "%s: Image package area %s is not valid\n" \
	    "$0" "$PKG_IMG_PATH"
	exit 1
fi
cd $PKG_IMG_PATH
mkdir miscdirs
mv opt miscdirs
mv etc miscdirs
mv var miscdirs
$MKISOFS -o solarismisc.zlib -N -l -R -U -allow-multidot \
    -no-iso-translate \
    -quiet -cache-inodes -d -D -V "compress" miscdirs
if [ "$?" != "0" ] ; then
	print -u2 -f "%s: mkisofs of solarismisc failed\n" "$0"
	exit 1	
fi
rm -rf miscdirs

COMPRESSION_TYPE=lzma
print "Compressing misc filesystem image using compression algorithm: ${COMPRESSION_TYPE}"
LD_LIBRARY_PATH=${PKG_IMG_PATH}/usr/lib $TIME ${PKG_IMG_PATH}${LOFIADM} \
    -C $COMPRESSION_TYPE ${PKG_IMG_PATH}/solarismisc.zlib >/dev/null 2>&1
if [ "$?" != "0" ] ; then
	print -u2 -f "%s: compression of solarismisc failed\n" "$0"
	exit 1	
fi
mv ${PKG_IMG_PATH}/solarismisc.zlib ${BA_BUILD}

exit 0
